import Dexie, { Table } from 'dexie'

export interface HabitSheet {
  id: string
  slug: string
  createdAt: Date
  updatedAt: Date
}

export interface Habit {
  id: string
  sheetId: string
  name: string
  group: string
  completions: Record<string, boolean>
  order: number
  createdAt: Date
  updatedAt: Date
}

export interface SyncQueueItem {
  id?: number // Auto-generated by Dexie
  type: 'CREATE_HABIT' | 'UPDATE_HABIT' | 'DELETE_HABIT' | 'FULL_SYNC'
  habitId?: string
  habitData?: any // The full habit data for CREATE/UPDATE
  deletedHabitIds?: string[] // For DELETE_HABIT batch
  timestamp: number
  retryCount?: number
  lastRetry?: number
}

export class HabitDatabase extends Dexie {
  habitSheets!: Table<HabitSheet>
  habits!: Table<Habit>
  syncQueue!: Table<SyncQueueItem>

  constructor() {
    super('HabitTrackerDB')
    this.version(1).stores({
      habitSheets: 'id, slug, updatedAt',
      habits: 'id, sheetId, group, order, updatedAt',
      syncQueue: '++id, type, habitId, timestamp'
    })
  }
}

export const db = new HabitDatabase()

// Queue a full sync (all habits from sheet)
export async function queueFullSync(sheetId: string, deletedHabitIds: string[] = []) {
  const habits = await db.habits.where('sheetId').equals(sheetId).toArray()
  await db.syncQueue.add({
    type: 'FULL_SYNC',
    habitData: { habits, deletedHabitIds },
    timestamp: Date.now(),
    retryCount: 0,
  })
}

// Queue a habit update
export async function queueHabitUpdate(habit: Habit, deletedIds: string[] = []) {
  await db.syncQueue.add({
    type: 'UPDATE_HABIT',
    habitId: habit.id,
    habitData: habit,
    deletedHabitIds: deletedIds,
    timestamp: Date.now(),
    retryCount: 0,
  })
}

// Get all pending sync items
export async function getPendingSyncItems(): Promise<SyncQueueItem[]> {
  return await db.syncQueue.toArray()
}

// Get sync item IDs for clearing
export async function getSyncItemIds(): Promise<number[]> {
  const items = await db.syncQueue.toArray()
  return items.map(item => item.id as number)
}

// Clear synced items
export async function clearSyncedItems(itemIds: number[]) {
  await db.syncQueue.where('id').anyOf(itemIds).delete()
}

// Get pending items that are ready for retry (exponential backoff)
export async function getItemsReadyForRetry(): Promise<SyncQueueItem[]> {
  const allItems = await db.syncQueue.toArray()
  const now = Date.now()

  return allItems.filter(item => {
    const retryCount = item.retryCount || 0
    const lastRetry = item.lastRetry || item.timestamp

    // Exponential backoff: 1s, 2s, 4s, 8s, 16s, 32s, max 60s
    const backoffMs = Math.min(60000, Math.pow(2, retryCount) * 1000)
    return (now - lastRetry) >= backoffMs
  })
}

// Update retry count for items
export async function markRetryFailed(itemIds: number[]) {
  const items = await db.syncQueue.where('id').anyOf(itemIds).toArray()
  await Promise.all(items.map(item =>
    db.syncQueue.update(item.id!, {
      retryCount: (item.retryCount || 0) + 1,
      lastRetry: Date.now(),
    })
  ))
}

// Count pending items
export async function getPendingSyncCount(): Promise<number> {
  return await db.syncQueue.count()
}

// Save or update habit sheet locally
export async function saveHabitSheet(sheet: HabitSheet) {
  await db.habitSheets.put(sheet)
}

// Save or update habit locally
export async function saveHabit(habit: Habit) {
  await db.habits.put(habit)
}

// Get habits for a sheet
export async function getHabitsForSheet(sheetId: string): Promise<Habit[]> {
  return await db.habits.where('sheetId').equals(sheetId).toArray()
}

// Get habit by ID
export async function getHabit(habitId: string): Promise<Habit | undefined> {
  return await db.habits.get(habitId)
}

// Delete habit locally
export async function deleteHabit(habitId: string) {
  await db.habits.delete(habitId)
}

// Get sheet by slug
export async function getHabitSheet(slug: string): Promise<HabitSheet | undefined> {
  return await db.habitSheets.where('slug').equals(slug).first()
}

// Get all sheets (for "my sheets" list)
export async function getAllHabitSheets(): Promise<HabitSheet[]> {
  return await db.habitSheets.toArray()
}
